# Generated by Django 5.1.3 on 2024-11-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("completed", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
